title: Cesar's Ramirez CIT_481 Blog 9_2022

logo: /assets/img/Github-vs-Bitbucket.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
